#!/usr/bin/env python3
"""Materialize shared/ sources and designated cross-skill scripts into
self-contained skill copies.

One-way, deterministic: the mapped sources are the only place devs edit;
committed copies inside skills are what skills.sh installs. Run with --check
(CI/L0) to fail on drift instead of writing.

Also writes the generated-file attributes into .gitattributes, derived from
SYNC_MAP rather than hand-listed: a hand-written list is a third copy of the
same knowledge and goes stale the first time a destination is added.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

MD_HEADER = "<!-- GENERATED from shared/ — edit shared/, then run scripts/sync_shared.py -->\n\n"
JSON_HEADER_KEY = "_generated"

# source (repo-relative) -> list of destination directories (repo-relative)
SYNC_MAP: dict[str, list[str]] = {
    "shared/guidelines/guidelines.md": [
        "skills/proposal-write/references",
        "skills/proposal-review/references",
        "skills/proposal-customize/references",
        "skills/proposal-ideate/references",
        # supervise applies the review rubric itself, so the semantic rules
        # travel with it
        "skills/proposal-supervise/references",
    ],
    "shared/structure.json": [
        "skills/proposal-check/references",
        # import and write verify their own output; check.py resolves the
        # skeleton relative to its own location, so the copy travels with
        # the script
        "skills/proposal-import/references",
        "skills/proposal-write/references",
        "skills/proposal-reverse/references",
        "skills/proposal-supervise/references",
        # troubleshoot needs the canonical titles as a redaction allowlist: a
        # backticked span in captured script output is kept only when it is a
        # canonical title, since anything else may be the student's own wording
        "skills/proposal-troubleshoot/references",
        # publish infers the proposal language from the canonical subtitle
        # wordings and section titles, and reads the references-section
        # headline it must leave unnumbered
        "skills/proposal-publish/references",
        # customize reproduces values from the skeleton verbatim — the default
        # forbidden list when re-allowing one entry (lists replace), shipped
        # branch ids when disabling one — and its SKILL.md and shipped
        # guidelines.md both name the file
        "skills/proposal-customize/references",
    ],
    # import and write run the check over the file they just wrote before
    # reporting, so the script is core to their function and ships as a
    # synchronized copy rather than a sibling fallback (packaging spec)
    "skills/proposal-check/scripts/check.py": [
        "skills/proposal-import/scripts",
        "skills/proposal-write/scripts",
        # reverse verifies its own fresh output before reporting, exactly as
        # import does, so the script is core to it rather than enrichment
        "skills/proposal-reverse/scripts",
        # supervise runs the mechanical check over the file it normalized
        "skills/proposal-supervise/scripts",
    ],
    # common+crossref vendored into import: validate_refs.py imports them as
    # Python modules, so a missing sibling would crash rather than degrade.
    # Ideate instead uses the sibling-fallback path (packaging spec).
    "skills/proposal-lit-search/scripts/common.py": [
        "skills/proposal-import/scripts",
        "skills/proposal-reverse/scripts",
    ],
    "skills/proposal-lit-search/scripts/crossref.py": [
        "skills/proposal-import/scripts",
        "skills/proposal-reverse/scripts",
    ],
    # reference validation is import's own script; reverse needs the identical
    # pass over the bibliography it carried across, so import owns it and
    # reverse takes a copy
    "skills/proposal-import/scripts/validate_refs.py": [
        "skills/proposal-reverse/scripts",
    ],
    # troubleshoot consults the support verdicts from a user's workspace, which
    # can reach neither this repository nor the network, so the data ships with
    # the skill. Regenerated by harness/report.py from the eval logs.
    "shared/model-support.json": ["skills/proposal-troubleshoot/references"],
}


BLOCKS = REPO / "shared" / "blocks"
SKILLS = REPO / "skills"
# The reporter is where the offer leads, so it carries no offer and no closing
# section; its absence is not drift (skill-packaging spec).
REPORTER = "proposal-troubleshoot"
OFFER_HEADING = "## When this run fails"
# Positions the skill-packaging spec fixes and test_skill_header_pattern.py
# already enforces. Anchoring here rather than on inserted markers keeps the
# rendered page free of banners and keeps the anchor something a contributor
# cannot silently move.
WORKFLOW_INDEX = 2
VOICE_INDEX = 3


class AnchorError(RuntimeError):
    """A region could not be located, so nothing is written for that skill."""


def skill_dirs() -> list[Path]:
    return sorted(d for d in SKILLS.iterdir() if d.is_dir() and d.name.startswith("proposal-"))


def split_frontmatter(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        raise AnchorError("no frontmatter")
    end = text.index("\n---\n", 3) + len("\n---\n")
    return text[:end], text[end:]


def header_spans(body: str) -> list[tuple[int, int]]:
    """Spans of the blank-line-separated blocks before the first `## ` heading."""
    limit = body.index("\n## ") if "\n## " in body else len(body)
    spans, start = [], None
    for pos, line in _lines_with_offsets(body[:limit]):
        if line.strip():
            start = pos if start is None else start
        elif start is not None:
            spans.append((start, pos - 1))
            start = None
    if start is not None:
        spans.append((start, limit))
    return spans


def _lines_with_offsets(text: str):
    pos = 0
    for line in text.splitlines(keepends=True):
        yield pos, line
        pos += len(line)


def offer_span(body: str) -> tuple[int, int]:
    """Span of the first paragraph after the closing section's heading."""
    if OFFER_HEADING not in body:
        raise AnchorError(f"no {OFFER_HEADING!r} section")
    after = body.index(OFFER_HEADING) + len(OFFER_HEADING)
    rest = body[after:]
    start = after + len(rest) - len(rest.lstrip("\n"))
    end = body.index("\n\n", start) if "\n\n" in body[start:] else len(body.rstrip("\n"))
    return start, end


def workflow_line(skill: str) -> str:
    """The shared line with this skill's own name marked."""
    line = (BLOCKS / "workflow.md").read_text(encoding="utf-8").strip()
    marked = line.replace(f" {skill} ", f" **{skill}** ").replace(f" {skill}.", f" **{skill}**.")
    if marked == line:
        raise AnchorError(f"{skill} is not named in shared/blocks/workflow.md")
    return marked


def render_skill_md(skill_dir: Path) -> str:
    """The SKILL.md this skill should have, with its shared regions materialized."""
    text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
    front, body = split_frontmatter(text)
    spans = header_spans(body)
    if len(spans) <= VOICE_INDEX:
        raise AnchorError(f"{skill_dir.name}: only {len(spans)} opening blocks")
    replacements = {
        spans[WORKFLOW_INDEX]: workflow_line(skill_dir.name),
        spans[VOICE_INDEX]: (BLOCKS / "voice.md").read_text(encoding="utf-8").strip(),
    }
    if skill_dir.name != REPORTER:
        replacements[offer_span(body)] = (
            (BLOCKS / "report-offer.md").read_text(encoding="utf-8").strip()
        )
    for (start, end), block in sorted(replacements.items(), reverse=True):
        body = body[:start] + block + body[end:]
    return front + body


def render(source: Path) -> str:
    # Headers are written into committed files, so the path must render the same
    # on every host: .as_posix() or a Windows sync rewrites every generated copy
    # with backslashes and the drift check fails on a fresh Windows clone.
    rel = source.relative_to(REPO).as_posix()
    text = source.read_text(encoding="utf-8")
    if source.suffix == ".md":
        return MD_HEADER + text
    if source.suffix == ".json":
        data = json.loads(text)
        header = f"from {rel} — edit there, then run scripts/sync_shared.py"
        stamped = {JSON_HEADER_KEY: header, **data}
        return json.dumps(stamped, ensure_ascii=False, indent=2) + "\n"
    if source.suffix == ".py":
        # two lines, so the banner stays inside the line-length limit whatever
        # the source path is
        header = (
            f"# GENERATED from {rel}\n"
            "# Edit there, then run scripts/sync_shared.py\n"
        )
        lines = text.split("\n", 1)
        if lines[0].startswith("#!"):
            return lines[0] + "\n" + header + (lines[1] if len(lines) > 1 else "")
        return header + text
    return text


GITATTRIBUTES = REPO / ".gitattributes"
BEGIN_MARK = "# BEGIN generated (scripts/sync_shared.py)"
END_MARK = "# END generated"
# merge=ours: the copy is derived, so the source is what merges. An unregistered
# driver is inert, which fails open to an ordinary conflict — `poe setup`
# registers it.
ATTRIBUTES = "linguist-generated=true merge=ours"


def generated_paths() -> list[str]:
    """Every destination SYNC_MAP writes, repo-relative and sorted."""
    return sorted(
        f"{dest_dir}/{Path(src_rel).name}"
        for src_rel, dest_dirs in SYNC_MAP.items()
        for dest_dir in dest_dirs
    )


def attribute_block() -> str:
    lines = [BEGIN_MARK, *(f"{p} {ATTRIBUTES}" for p in generated_paths()), END_MARK]
    return "\n".join(lines) + "\n"


def render_gitattributes(current: str) -> str:
    """Replace the generated block, keeping hand-written lines around it."""
    block = attribute_block()
    if BEGIN_MARK not in current:
        return current + ("\n" if current and not current.endswith("\n") else "") + block
    head, _, rest = current.partition(BEGIN_MARK)
    _, _, tail = rest.partition(END_MARK + "\n")
    return head + block + tail


def _materialize(dest: Path, expected: str, src_label: str, check: bool) -> str | None:
    """Write or verify one destination; returns its path when it has drifted.

    The one place the write/check branch lives, so each pass below is a loop over
    destinations and nothing else. The printed line is exactly
    "synced <src> -> <dst>": .githooks/pre-commit reads its fourth field and
    stages it.
    """
    rel = dest.relative_to(REPO).as_posix()
    if check:
        stale = not dest.exists() or dest.read_text(encoding="utf-8") != expected
        return rel if stale else None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(expected, encoding="utf-8")
    print(f"synced {src_label} -> {rel}")
    return None


def _sync_attributes(check: bool) -> list[str]:
    current = GITATTRIBUTES.read_text(encoding="utf-8") if GITATTRIBUTES.exists() else ""
    drifted = _materialize(GITATTRIBUTES, render_gitattributes(current), "SYNC_MAP", check)
    return [drifted] if drifted else []


def _sync_skill_blocks(check: bool) -> list[str]:
    drift = [
        _materialize(d / "SKILL.md", render_skill_md(d), "shared/blocks", check)
        for d in skill_dirs()
    ]
    return [rel for rel in drift if rel]


def _sync_copies(check: bool) -> list[str]:
    drift = []
    for src_rel, dest_dirs in SYNC_MAP.items():
        source = REPO / src_rel
        expected = render(source)
        for dest_dir in dest_dirs:
            drift.append(_materialize(REPO / dest_dir / source.name, expected, src_rel, check))
    return [rel for rel in drift if rel]


def sync(check: bool) -> int:
    drift = _sync_attributes(check) + _sync_skill_blocks(check) + _sync_copies(check)
    if check and drift:
        print("OUT OF SYNC (run scripts/sync_shared.py):", *drift, sep="\n  ")
        return 1
    if check:
        print("generated copies in sync")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify copies instead of writing")
    return sync(parser.parse_args(argv).check)


if __name__ == "__main__":
    sys.exit(main())
