#!/usr/bin/env python3
"""Materialize shared/ sources and designated cross-skill scripts into
self-contained skill copies.

One-way, deterministic: the mapped sources are the only place devs edit;
committed copies inside skills are what skills.sh installs. Run with --check
(CI/L0) to fail on drift instead of writing.

Also writes the generated-file attributes into .gitattributes, derived from
SYNC_MAP rather than hand-listed: a hand-written list is a third copy of the
same knowledge and goes stale the first time a destination is added.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

MD_HEADER = "<!-- GENERATED from shared/ — edit shared/, then run scripts/sync_shared.py -->\n\n"
JSON_HEADER_KEY = "_generated"

# source (repo-relative) -> list of destination directories (repo-relative)
SYNC_MAP: dict[str, list[str]] = {
    "shared/guidelines/guidelines.md": [
        "skills/proposal-write/references",
        "skills/proposal-review/references",
        "skills/proposal-customize/references",
        "skills/proposal-ideate/references",
        # supervise applies the review rubric itself, so the semantic rules
        # travel with it
        "skills/proposal-supervise/references",
    ],
    "shared/structure.json": [
        "skills/proposal-check/references",
        # import and write verify their own output; check.py resolves the
        # skeleton relative to its own location, so the copy travels with
        # the script
        "skills/proposal-import/references",
        "skills/proposal-write/references",
        "skills/proposal-supervise/references",
        # troubleshoot needs the canonical titles as a redaction allowlist: a
        # backticked span in captured script output is kept only when it is a
        # canonical title, since anything else may be the student's own wording
        "skills/proposal-troubleshoot/references",
    ],
    # import and write run the check over the file they just wrote before
    # reporting, so the script is core to their function and ships as a
    # synchronized copy rather than a sibling fallback (packaging spec)
    "skills/proposal-check/scripts/check.py": [
        "skills/proposal-import/scripts",
        "skills/proposal-write/scripts",
        # supervise runs the mechanical check over the file it normalized
        "skills/proposal-supervise/scripts",
    ],
    # common+crossref vendored into import: validate_refs.py imports them as
    # Python modules, so a missing sibling would crash rather than degrade.
    # Ideate instead uses the sibling-fallback path (packaging spec).
    "skills/proposal-lit-search/scripts/common.py": ["skills/proposal-import/scripts"],
    "skills/proposal-lit-search/scripts/crossref.py": ["skills/proposal-import/scripts"],
    # troubleshoot consults the support verdicts from a user's workspace, which
    # can reach neither this repository nor the network, so the data ships with
    # the skill. Regenerated by harness/report.py from the eval logs.
    "shared/model-support.json": ["skills/proposal-troubleshoot/references"],
}


def render(source: Path) -> str:
    # Headers are written into committed files, so the path must render the same
    # on every host: .as_posix() or a Windows sync rewrites every generated copy
    # with backslashes and the drift check fails on a fresh Windows clone.
    rel = source.relative_to(REPO).as_posix()
    text = source.read_text(encoding="utf-8")
    if source.suffix == ".md":
        return MD_HEADER + text
    if source.suffix == ".json":
        data = json.loads(text)
        header = f"from {rel} — edit there, then run scripts/sync_shared.py"
        stamped = {JSON_HEADER_KEY: header, **data}
        return json.dumps(stamped, ensure_ascii=False, indent=2) + "\n"
    if source.suffix == ".py":
        # two lines, so the banner stays inside the line-length limit whatever
        # the source path is
        header = (
            f"# GENERATED from {rel}\n"
            "# Edit there, then run scripts/sync_shared.py\n"
        )
        lines = text.split("\n", 1)
        if lines[0].startswith("#!"):
            return lines[0] + "\n" + header + (lines[1] if len(lines) > 1 else "")
        return header + text
    return text


GITATTRIBUTES = REPO / ".gitattributes"
BEGIN_MARK = "# BEGIN generated (scripts/sync_shared.py)"
END_MARK = "# END generated"
# merge=ours: the copy is derived, so the source is what merges. An unregistered
# driver is inert, which fails open to an ordinary conflict — `poe setup`
# registers it.
ATTRIBUTES = "linguist-generated=true merge=ours"


def generated_paths() -> list[str]:
    """Every destination SYNC_MAP writes, repo-relative and sorted."""
    return sorted(
        f"{dest_dir}/{Path(src_rel).name}"
        for src_rel, dest_dirs in SYNC_MAP.items()
        for dest_dir in dest_dirs
    )


def attribute_block() -> str:
    lines = [BEGIN_MARK, *(f"{p} {ATTRIBUTES}" for p in generated_paths()), END_MARK]
    return "\n".join(lines) + "\n"


def render_gitattributes(current: str) -> str:
    """Replace the generated block, keeping hand-written lines around it."""
    block = attribute_block()
    if BEGIN_MARK not in current:
        return current + ("\n" if current and not current.endswith("\n") else "") + block
    head, _, rest = current.partition(BEGIN_MARK)
    _, _, tail = rest.partition(END_MARK + "\n")
    return head + block + tail


def sync(check: bool) -> int:
    drift: list[str] = []
    current = GITATTRIBUTES.read_text(encoding="utf-8") if GITATTRIBUTES.exists() else ""
    expected_attrs = render_gitattributes(current)
    if check:
        if current != expected_attrs:
            drift.append(".gitattributes")
    else:
        GITATTRIBUTES.write_text(expected_attrs, encoding="utf-8")
        # exactly "synced <src> -> <dst>": .githooks/pre-commit reads the fourth
        # field of each line and stages it
        print("synced SYNC_MAP -> .gitattributes")
    for src_rel, dest_dirs in SYNC_MAP.items():
        source = REPO / src_rel
        expected = render(source)
        for dest_dir in dest_dirs:
            dest = REPO / dest_dir / source.name
            if check:
                if not dest.exists() or dest.read_text(encoding="utf-8") != expected:
                    drift.append(dest.relative_to(REPO).as_posix())
            else:
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(expected, encoding="utf-8")
                print(f"synced {src_rel} -> {dest.relative_to(REPO).as_posix()}")
    if check and drift:
        print("OUT OF SYNC (run scripts/sync_shared.py):", *drift, sep="\n  ")
        return 1
    if check:
        print("generated copies in sync")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify copies instead of writing")
    return sync(parser.parse_args(argv).check)


if __name__ == "__main__":
    sys.exit(main())
